name: Code Quality

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    ESLint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js 18
              uses: actions/setup-node@v2
              with:
                  node-version: 18
            - name: Restore CI Cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-18-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies
              run: yarn
            - name: Run ESLint
              uses: icrawl/action-eslint@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  job-name: ESLint

    Typescript:
        name: Typescript
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js 18
              uses: actions/setup-node@v2
              with:
                  node-version: 18
            - name: Restore CI Cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-18-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies
              run: yarn
            - name: Run TSC
              uses: icrawl/action-tsc@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  job-name: Typescript
